name: Deploy Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2 # It's safer to use stable versions rather than 'main'

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build & Push Image'
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/test:latest
          docker push ghcr.io/${{ github.repository_owner }}/test:latest
