name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Actions
        uses: actions/checkout@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the image
        run: |
          docker build . --tag ghcr.io/surjeetrai/hello:latest
          docker push ghcr.io/surjeetrai/hello:latest

        
